Match BBHN Defaults
Use BBHN init script that does not depend on external functions
Add old secure key into default configuration.

diff --git a/files/olsrd.init b/files/olsrd.init
--- a/files/olsrd.init
+++ b/files/olsrd.init
@@ -1,36 +1,27 @@
 #!/bin/sh /etc/rc.common
-# Copyright (C) 2008-2013 OpenWrt.org
-
+# Copyright (C) 2008  Alina Friedrichsen <x-alina@gmx.net>
+# Special thanks to bittorf wireless ))
 START=65
-
-SERVICE_DAEMONIZE=1
-SERVICE_WRITE_PID=1
-
-CONF=/var/etc/olsrd.conf
-PID=/var/run/olsrd.pid
-PID6=/var/run/olsrd.ipv6.pid
 
 OLSRD_OLSRD_SCHEMA='ignore:internal config_file:internal DebugLevel=0 AllowNoInt=yes'
 OLSRD_IPCCONNECT_SCHEMA='ignore:internal Host:list Net:list2'
 OLSRD_LOADPLUGIN_SCHEMA='ignore:internal library:internal Host4:list Net4:list2 Host:list Net:list2 Host6:list Net6:list2 Ping:list redistribute:list NonOlsrIf:list name:list lat lon latlon_infile HNA:list2 hosts:list2'
-OLSRD_INTERFACE_SCHEMA='ignore:internal interface:internal AutoDetectChanges:bool LinkQualityMult:list2'
+OLSRD_INTERFACE_SCHEMA='ignore:internal interface:internal AutoDetectChanges:bool'
 OLSRD_INTERFACE_DEFAULTS_SCHEMA='AutoDetectChanges:bool'
 
 T='	'
 N='
 '
 
-log() {
-	logger -t olsrd -p daemon.info -s "${initscript}: $@"
-}
-
-error() {
-	log "ERROR: $@"
-}
-
 validate_varname() {
 	local varname="$1"
 	[ -z "$varname" -o "$varname" != "${varname%%[!A-Za-z0-9_]*}" ] && return 1
+	return 0
+}
+
+validate_ifname() {
+	local ifname="$1"
+	[ -z "$ifname" -o "$ifname" != "${ifname%%[!A-Za-z0-9.:_-]*}" ] && return 1
 	return 0
 }
 
@@ -40,9 +31,24 @@ validate_olsrd_option() {
 	return 0
 }
 
+get_ifname() {
+	IFNAME=
+	local interface="$1"
+	validate_varname "$interface" || return 1
+	local ifname
+
+	config_get ifname "$interface" ifname
+	validate_ifname "$ifname" || return 1
+	IFNAME="$ifname"
+
+	return 0
+}
+
 system_config() {
 	local cfg="$1"
-	local cfgt hostname latlon oldIFS
+	local cfgt
+	local hostname
+	local latlon
 
 	config_get cfgt "$cfg" TYPE
 
@@ -54,7 +60,9 @@ system_config() {
 
 	if [ -z "$SYSTEM_LAT" -o -z "$SYSTEM_LON" ]; then
 		config_get latlon "$cfg" latlon
-		oldIFS="$IFS"; IFS=" ${T}${N},"; set -- $latlon; IFS="$oldIFS"
+		IFS=" ${T}${N},"
+		set -- $latlon
+		unset IFS
 		SYSTEM_LAT="$1"
 		SYSTEM_LON="$2"
 	fi
@@ -79,7 +87,6 @@ olsrd_find_config_file() {
 }
 
 warning_invalid_value() {
-	local funcname="warning_invalid_value"
 	local package="$1"
 	validate_varname "$package" || package=
 	local config="$2"
@@ -87,11 +94,13 @@ warning_invalid_value() {
 	local option="$3"
 	validate_varname "$option" || option=
 
+	echo -n "Warning: Invalid value" 1>&2
+
 	if [ -n "$package" -a -n "$config" ]; then
-		log "$funcname() in option '$package.$config${option:+.}$option', skipped"
-	else
-		log "$funcname() skipped"
+		echo -n " in option '$package.$config${option:+.}$option'" 1>&2
 	fi
+
+	echo ", skipped" 1>&2
 
 	return 0
 }
@@ -130,7 +139,6 @@ olsrd_write_option() {
 }
 
 olsrd_write_plparam() {
-	local funcname="olsrd_write_plparam"
 	local param="$1"
 	local cfg="$2"
 	validate_varname "$cfg" || return 1
@@ -138,7 +146,7 @@ olsrd_write_plparam() {
 	validate_varname "$option" || return 1
 	local value="$4"
 	local option_type="$5"
-	local _option oldIFS
+	local _option
 
 	if [ "$option_type" = bool ]; then
 		case "$value" in
@@ -153,26 +161,24 @@ olsrd_write_plparam() {
 		return 1
 	fi
 
-	oldIFS="$IFS"
 	IFS='-_'
 	set -- $option
 	option="$*"
-	IFS="$oldIFS"
+	unset IFS
 	_option="$option"
-
 	if [ "$option" = 'hosts' ]; then
 		set -- $value
 		option="$1"
 		shift
 		value="$*"
 	fi
-
 	if [ "$option" = 'NonOlsrIf' ]; then
 		if validate_varname "$value"; then
-			if network_get_device ifname "$value"; then
-				log "$funcname() Info: mdns Interface '$value' ifname '$ifname' found"
+			if get_ifname "$value"; then
+				ifname="$IFNAME"
+				echo "Info: mdns Interface '$value' ifname '$ifname' found" 1>&2
 			else
-				log "$funcname() Warning: mdns Interface '$value' not found, skipped"
+				echo "Warning: mdns Interface '$value' not found, skipped" 1>&2
 			fi
 		else
 			warning_invalid_value olsrd "$cfg" "NonOlsrIf"
@@ -186,6 +192,7 @@ olsrd_write_plparam() {
 }
 
 config_update_schema() {
+	unset IFS
 	local schema_varname="$1"
 	validate_varname "$schema_varname" || return 1
 	local command="$2"
@@ -226,119 +233,43 @@ config_update_schema() {
 }
 
 config_write_options() {
-	local funcname="config_write_options"
+	unset IFS
 	local schema="$1"
 	local cfg="$2"
 	validate_varname "$cfg" || return 1
 	local write_func="$3"
 	[ -z "$write_func" ] && output_func=echo
 	local write_param="$4"
+	local schema_entry
+	local option
+	local option_length
+	local option_type
+	local default
+	local value
+	local list_size
+	local list_item
+	local list_value
+	local i
+	local position
 
-	local schema_entry option option_length option_type default value list_size list_item list_value i position speed oldIFS
-	local list_speed_vars="HelloInterval HelloValidityTime TcInterval TcValidityTime MidInterval MidValidityTime HnaInterval HnaValidityTime"
-
-	get_value_for_entry()
-	{
-		local schema_entry="$1"
-
+	for schema_entry in $schema; do
 		default="${schema_entry#*[=]}"
 		[ "$default" = "$schema_entry" ] && default=
 		option="${schema_entry%%[=]*}"
-
-		oldIFS="$IFS"; IFS=':'; set -- $option; IFS="$oldIFS"
+		IFS=':'
+		set -- $option
+		unset IFS
 		option="$1"
 		option_type="$2"
-
-		validate_varname "$option" || return 1
-		[ -z "$option_type" ] || validate_varname "$option_type" || return 1
-		[ "$option_type" = internal ] && return 1
-
+		validate_varname "$option" || continue
+		[ -z "$option_type" ] || validate_varname "$option_type" || continue
+		[ "$option_type" = internal ] && continue
 		config_get value "$cfg" "$option"
-		[ "$option" = "speed" ] && return 1
-
-		return 0
-	}
-
-	already_in_schema()
-	{
-		case " $schema " in
-			*" $1 "*)
-				return 0
-			;;
-			*)
-				return 1
-			;;
-		esac
-	}
-
-	already_in_schema "speed" && {
-		get_value_for_entry "speed"
-
-		if [ 2>/dev/null $value -gt 0 -a $value -le 20 ]; then
-			speed="$value"
-		else
-			log "$funcname() Warning: invalid speed-value: '$value' - allowed integers: 1...20, fallback to 6"
-			speed=6
-		fi
-
-		for schema_entry in $list_speed_vars; do {
-			already_in_schema "$schema_entry" || schema="$schema $schema_entry"
-		} done
-	}
-
-	for schema_entry in $schema; do
-		if [ -n "$speed" ]; then		# like sven-ola freifunk firmware fff-1.7.4
-			case "$schema_entry" in
-				HelloInterval)
-					value="$(( $speed / 2 + 1 )).0"
-				;;
-				HelloValidityTime)
-					value="$(( $speed * 25 )).0"
-				;;
-				TcInterval)	# todo: not fisheye? -> $(( $speed * 2 ))
-					value=$(( $speed / 2 ))
-					[ $value -eq 0 ] && value=1
-					value="$value.0"
-				;;
-				TcValidityTime)
-					value="$(( $speed * 100 )).0"
-				;;
-				MidInterval)
-					value="$(( $speed * 5 )).0"
-				;;
-				MidValidityTime)
-					value="$(( $speed * 100 )).0"
-				;;
-				HnaInterval)
-					value="$(( $speed * 2 )).0"
-				;;
-				HnaValidityTime)
-					value="$(( $speed * 25 )).0"
-				;;
-				*)
-					get_value_for_entry "$schema_entry" || continue
-				;;
-			esac
-
-			is_speed_var()
-			{
-				case " $list_speed_vars " in
-					*" $1 "*)
-						return 0
-					;;
-					*)
-						return 1
-					;;
-				esac
-			}
-
-			is_speed_var "$schema_entry" && option="$schema_entry"
-		else
-			get_value_for_entry "$schema_entry" || continue
-		fi
 
 		if [ -z "$value" ]; then
-			oldIFS="$IFS"; IFS='+'; set -- $default; IFS="$oldIFS"
+			IFS='+'
+			set -- $default
+			unset IFS
 			value=$*
 		elif [ "$value" = '-' -a -n "$default" ]; then
 			continue
@@ -388,6 +319,7 @@ olsrd_write_olsrd() {
 	local cfg="$1"
 	validate_varname "$cfg" || return 0
 	local ignore
+	local ipversion
 
 	config_get_bool ignore "$cfg" ignore 0
 	[ "$ignore" -ne 0 ] && return 0
@@ -399,12 +331,11 @@ olsrd_write_olsrd() {
 		OLSRD_IPVERSION_6AND4=1
 		config_set "$cfg" IpVersion '6'
 	fi
-	config_get smartgateway "$cfg" SmartGateway
-	config_get smartgatewayuplink "$cfg" SmartGatewayUplink
 
 	config_write_options "$OLSRD_OLSRD_SCHEMA" "$cfg" olsrd_write_option
 	echo
 	OLSRD_COUNT=$((OLSRD_COUNT + 1))
+
 	return 0
 }
 
@@ -481,7 +412,6 @@ olsrd_write_hna6() {
 }
 
 olsrd_write_loadplugin() {
-	local funcname="olsrd_write_loadplugin"
 	local cfg="$1"
 	validate_varname "$cfg" || return 0
 	local ignore
@@ -500,7 +430,7 @@ olsrd_write_loadplugin() {
 		return 0
 	fi
 	if ! [ -x "/lib/$library" -o -x "/usr/lib/$library" -o -x "/usr/local/lib/$library" ]; then
-		log "$funcname() Warning: Plugin library '$library' not found, skipped"
+		echo "Warning: Plugin library '$library' not found, skipped" 1>&2
 		return 0
 	fi
 
@@ -526,14 +456,8 @@ olsrd_write_loadplugin() {
 				fi
 			fi
 
-			for f in latlon_file hosts_file services_file resolv_file macs_file; do
-				config_get $f "$cfg" $f
-			done
-
+			config_get latlon_file "$cfg" latlon_file
 			[ -z "$latlon_file" ] && config_set "$cfg" latlon_file '/var/run/latlon.js'
-		;;
-		olsrd_watchdog.*)
-			config_get wd_file "$cfg" file
 		;;
 	esac
 
@@ -545,7 +469,6 @@ olsrd_write_loadplugin() {
 }
 
 olsrd_write_interface() {
-	local funcname="olsrd_write_interface"
 	local cfg="$1"
 	validate_varname "$cfg" || return 0
 	local ignore
@@ -558,20 +481,12 @@ olsrd_write_interface() {
 
 	ifnames=
 	config_get interfaces "$cfg" interface
-
 	for interface in $interfaces; do
 		if validate_varname "$interface"; then
-			if network_get_device IFNAME "$interface"; then
+			if get_ifname "$interface"; then
 				ifnames="$ifnames \"$IFNAME\""
-				ifsglobal="$ifsglobal $IFNAME"
-			elif network_get_physdev IFNAME "$interface"; then
-				local proto="$(uci -q get network.${interface}.proto)"
-				if [ "$proto" = "static" -o "$proto" = "none" ]; then
-					ifnames="$ifnames \"$IFNAME\""
-					ifsglobal="$ifsglobal $IFNAME"
-				fi
 			else
-				log "$funcname() Warning: Interface '$interface' not found, skipped"
+				echo "Warning: Interface '$interface' not found, skipped" 1>&2
 			fi
 		else
 			warning_invalid_value olsrd "$cfg" "interface"
@@ -637,116 +552,10 @@ olsrd_write_config() {
 	INTERFACES_COUNT=0
 	config_foreach olsrd_write_interface_defaults InterfaceDefaults
 	config_foreach olsrd_write_interface Interface
+	/usr/local/bin/olsrd-config
 	echo
 
 	return 0
-}
-
-get_wan_ifnames()
-{
-	local wanifnames word catch_next
-
-	which ip >/dev/null || return 1
-
-	set -- $( ip route list exact 0.0.0.0/0 table all )
-	for word in $*; do
-		case "$word" in
-			dev)
-				catch_next="true"
-			;;
-			*)
-				[ -n "$catch_next" ] && {
-					case "$wanifnames" in
-						*" $word "*)
-						;;
-						*)
-							wanifnames="$wanifnames $word "
-						;;
-					esac
-
-					catch_next=
-				}
-			;;
-		esac
-	done
-
-	echo "$wanifnames"
-}
-
-olsrd_setup_smartgw_rules() {
-	local funcname="olsrd_setup_smartgw_rules"
-	# Check if ipip is installed
-	[ -e /etc/modules.d/[0-9]*-ipip ] || {
-		log "$funcname() Warning: kmod-ipip is missing. SmartGateway will not work until you install it."
-		return 1
-	}
-
-	local wanifnames="$( get_wan_ifnames )"
-
-	if [ -z "$wanifnames" ]; then
-		nowan=1
-	else
-		nowan=0
-	fi
-
-	IP4T=$(which iptables)
-	IP6T=$(which ip6tables)
-
-	# Delete smartgw firewall rules first
-	for IPT in $IP4T $IP6T; do
-		while $IPT -D forwarding_rule -o tnl_+ -j ACCEPT 2> /dev/null; do :;done
-		for IFACE in $wanifnames; do
-			while $IPT -D forwarding_rule -i tunl0 -o $IFACE -j ACCEPT 2> /dev/null; do :; done
-		done
-		for IFACE in $ifsglobal; do
-			while $IPT -D input_rule -i $IFACE -p 4 -j ACCEPT 2> /dev/null; do :; done
-		done
-	done
-	while $IP4T -t nat -D postrouting_rule -o tnl_+ -j MASQUERADE 2> /dev/null; do :;done
-
-	if [ "$smartgateway" == "yes" ]; then
-		log "$funcname() Notice: Inserting firewall rules for SmartGateway"
-		if [ ! "$smartgatewayuplink" == "none" ]; then
-			if [ "$smartgatewayuplink" == "ipv4" ]; then
-				# Allow everything to be forwarded to tnl_+ and use NAT for it
-				$IP4T -I forwarding_rule -o tnl_+ -j ACCEPT
-				$IP4T -t nat -I postrouting_rule -o tnl_+ -j MASQUERADE
-				# Allow forwarding from tunl0 to (all) wan-interfaces
-				if [ "$nowan"="0" ]; then
-					for IFACE in $wanifnames; do
-						$IP4T -A forwarding_rule -i tunl0 -o $IFACE -j ACCEPT
-					done
-				fi
-				# Allow incoming ipip on all olsr-interfaces
-				for IFACE in $ifsglobal; do
-					$IP4T -I input_rule -i $IFACE -p 4 -j ACCEPT
-				done
-			elif [ "$smartgatewayuplink" == "ipv6" ]; then
-				$IP6T -I forwarding_rule -o tnl_+ -j ACCEPT
-				if [ "$nowan"="0" ]; then
-					for IFACE in $wanifnames; do
-						$IP6T -A forwarding_rule -i tunl0 -o $IFACE -j ACCEPT
-					done
-				fi
-				for IFACE in $ifsglobal; do
-					$IP6T -I input_rule -i $IFACE -p 4 -j ACCEPT
-				done
-			else
-				for IPT in $IP4T $IP6T; do
-					$IPT -I forwarding_rule -o tnl_+ -j ACCEPT
-					$IPT -t nat -I postrouting_rule -o tnl_+ -j MASQUERADE
-					if [ "$nowan"="0" ]; then
-						for IFACE in $wanifnames; do
-							$IPT -A forwarding_rule -i tunl0 -o $IFACE -j ACCEPT
-						done
-					fi
-					for IFACE in $ifsglobal; do
-						$IPT -I input_rule -i $IFACE -p 4 -j ACCEPT
-					done
-				done
-			fi
-		fi
-	fi
 }
 
 start() {
@@ -764,8 +573,8 @@ start() {
 		olsrd_update_schema "list" "$@"
 	}
 
-	. /lib/functions/network.sh
-
+	include /lib/network
+	scan_interfaces
 	config_load olsrd
 	reset_cb
 
@@ -785,59 +594,20 @@ start() {
 	local bindv6only='0'
 	if [ "$OLSRD_IPVERSION_6AND4" -ne 0 ]; then
 		bindv6only="$(sysctl -n net.ipv6.bindv6only)"
-		sysctl -w net.ipv6.bindv6only=1 > /dev/null
-		sed -e '/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/d' < "$OLSRD_CONFIG_FILE" > /var/etc/olsrd.conf.ipv6
+		sysctl -w net.ipv6.bindv6only=1
+		sed -e 's/^\t\t[0-9.]*[ ][0-9.]*$//' < "$OLSRD_CONFIG_FILE" > /var/etc/olsrd.conf.ipv6
+		sed -i '/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/d' /var/etc/olsrd.conf.ipv6
+		olsrd -f /var/etc/olsrd.conf.ipv6 -nofork < /dev/null > /dev/null &
+
 		sed -e 's/^IpVersion[ ][ ]*6$/IpVersion 4/' -e 's/^\t\t[A-Fa-f0-9.:]*[:][A-Fa-f0-9.:]*[ ][0-9]*$//' < "$OLSRD_CONFIG_FILE" > /var/etc/olsrd.conf.ipv4
-		rm $OLSRD_CONFIG_FILE
-
-		# some filenames should get the suffix .ipv6
-		for file in $latlon_file $hosts_file $services_file $resolv_file $macs_file $wd_file;do
-			f=$(echo $file|sed 's/\//\\\//g')
-			sed -i "s/$f/$f.ipv6/g" /var/etc/olsrd.conf.ipv6
-		done
-
-		SERVICE_PID_FILE="$PID6"
-		if service_check /usr/sbin/olsrd; then
-			error "there is already an IPv6 instance of olsrd running (pid: '$(cat $PID6)'), not starting."
-		else
-			service_start /usr/sbin/olsrd -f /var/etc/olsrd.conf.ipv6 -nofork
-		fi
-
-		SERVICE_PID_FILE="$PID"
-		if service_check /usr/sbin/olsrd; then
-			error "there is already an IPv4 instance of olsrd running (pid: '$(cat $PID)'), not starting."
-		else
-			service_start /usr/sbin/olsrd -f /var/etc/olsrd.conf.ipv4 -nofork
-		fi
-
+		olsrd -f /var/etc/olsrd.conf.ipv4 -nofork < /dev/null > /dev/null &
 		sleep 3
-		sysctl -w net.ipv6.bindv6only="$bindv6only" > /dev/null
-
+		sysctl -w net.ipv6.bindv6only="$bindv6only"
 	else
-
-		if [ "$ipversion" = "6" ]; then
-			sed -i '/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/d' "$OLSRD_CONFIG_FILE"
-		fi
-
-		SERVICE_PID_FILE="$PID"
-		if service_check /usr/sbin/olsrd; then
-			error "there is already an IPv4 instance of olsrd running (pid: '$(cat $PID)'), not starting."
-			return 1
-		else
-			service_start /usr/sbin/olsrd -f "$OLSRD_CONFIG_FILE" -nofork
-			service_check /usr/sbin/olsrd || {
-				log "startup-error: check via: '/usr/sbin/olsrd -f \"$OLSRD_CONFIG_FILE\" -nofork'"
-			}
-		fi
+		olsrd -f "$OLSRD_CONFIG_FILE" -nofork < /dev/null > /dev/null &
 	fi
-
-	olsrd_setup_smartgw_rules
 }
 
 stop() {
-	SERVICE_PID_FILE="$PID"
-	service_stop /usr/sbin/olsrd
-
-	SERVICE_PID_FILE="$PID6"
-	service_stop /usr/sbin/olsrd
+	killall olsrd
 }
